project15/urls.py
from django.contrib import admin
from django.urls import path,include
from generic.views import *
import specific



urlpatterns = [
    path('admin/', admin.site.urls),
    path('munnabhi/',munnabhi,name='munnabhi'),
    path('guddubhayya/',guddubhayya,name='guddubhayya'),
    path('specific/',include('specific.urls')),
]

specific/urls.py
from specific.views import *
from django.urls import path

app_name='specific'


urlpatterns=[
    path('anil/',anil,name='anil'),
    path('venke/',venke,name='venke'),
]

generic/models.py
from django.db import models

# Create your models here.

specific/models.py
from django.db import models

# Create your models here.

generic/views.py
from django.shortcuts import render

# Create your views here.

def munnabhi(request):
    return render(request,'munnabhi.html')



def guddubhayya(request):
    return render(request,'guddubhayya.html')   

specific/views.py
from django.shortcuts import render

# Create your views here.


def anil(request):
    return render(request,'anil.html')



def venke(request):
    return render(request,'venke.html')   

templates/anil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> Usa me kaha gaya no </h1>
    </center>
</body>
</html>

templates/guddubhayya.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> welcome </h1>
    </center>
</body>
</html>

templates/munnabhi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>chadivi ias ifis avvakunda esi.........</h1>
    
    
    <a href="{% url 'guddubhayya' %}"></a>
    <a href="{% url ' specific:anil' %}"></a>
    <a href="{% url 'specific:venke' %}"></a>
    
    
    
    
    </center>
</body>
</html>

templates/venke.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> naalo antha vadi undhe ......... padastaa</h1>
    </center>
</body>
</html>